name: CD - Deploy Docker

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, macOS, ARM64]




    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > deploy_key
          chmod 600 deploy_key

      - name: Run deployment script on Mac mini
        run: |
          ssh -o StrictHostKeyChecking=no -i deploy_key hungtruong@127.0.0.1 "bash ~/deploy_food_ordering.sh"

     