name: CI Monitoring Metrics

on:
  push:
    branches: [ main ]

jobs:
  build-and-monitor:
    runs-on: self-hosted

    env:
      PUSHGATEWAY_URL: http://127.0.0.1:9091

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests & push metrics
        run: |
          start=$(date +%s)

          set +e
          npm test
          test_exit_code=$?
          set -e

          end=$(date +%s)
          duration=$((end - start))

          if [ $test_exit_code -eq 0 ]; then
            pipeline_status=1
          else
            pipeline_status=0
          fi

          cat <<EOF | curl --data-binary @- "$PUSHGATEWAY_URL/metrics/job/food_ordering_ci"
          cicd_pipeline_last_status{pipeline="food_ordering_ci"} $pipeline_status
          cicd_pipeline_duration_seconds{pipeline="food_ordering_ci"} $duration
          EOF

          exit $test_exit_code
