name: CI - Node App + k6 Performance

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test:
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start server for k6 testing
        run: |
          nohup npm start > server.log 2>&1 &
          sleep 5

      - name: Install k6
        run: |
          brew install k6

      - name: Run k6 performance test
        run: |
          k6 run loadtest.js

      - name: Show server logs if test FAIL
        if: failure()
        run: |
          echo "❗ SERVER LOG ❗"
          cat server.log
      - name: Send Pipeline Data to Datadog
        uses: Datadog/ci-visibility-github-action@v1
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          site: ${{ secrets.DD_SITE }}