name: CI - Node App + k6 Performance

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  k6-test:
    runs-on: self-hosted


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: |
          nohup npm start > server.log 2>&1 &
          sleep 7

      - name: Install k6
        run: sudo apt-get update && sudo apt-get install -y k6

      - name: Run k6 performance test
        run: k6 run loadtest.js

      - name: Show logs if fail
        if: failure()
        run: cat server.log
