name: CI - Build & Test Node App

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_SITE: "us5.datadoghq.com"
      DD_CIVISIBILITY_AGENTLESS_ENABLED: "true"

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci
          npm install -g @datadog/datadog-ci

      - name: Run Jest tests and upload to Datadog
        run: |
          # chạy test + xuất junit report
          npm test -- --reporters=default --reporters=jest-junit

          # upload test report lên Datadog
          datadog-ci junit upload \
            --service food-ordering \
            reports/junit.xml
